# -*- coding: utf-8 -*-
"""Live Weather Details.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxtYXv8IRLLSy-xviLkcwjmB6eEDgG9f

# Live Weather Details - Web Scrapping - Python


*   Author: Purva Natoo

##### Install necessary libraries
"""

!pip install bs4
!pip install requests

"""##### Import Dependencies"""

import requests
from bs4 import BeautifulSoup

"""##### Define a function to get data from a given url"""

def getData(url):
  data = requests.get(url)
  return data.text

"""##### Pass the url and get the html data"""

htmlData = getData("https://weather.com/weather/today/l/924f61ca28f5d5dad164c92a1cde87f262d71cb0e4e6370aa3307ea54687bd3a")
soup = BeautifulSoup(htmlData, "html.parser")
print(soup.prettify())

"""##### Find the temp data"""

currentTemp = soup.find_all("span", class_="CurrentConditions--tempValue--3a50n")
location = soup.find_all("h1", class_="CurrentConditions--location--kyTeL")
dayNightTemp = soup.find_all("div", class_="CurrentConditions--tempHiLoValue--3SUHy")

currentTemperature = (str(currentTemp))
currentTemperature = currentTemperature.replace("[<span class=\"CurrentConditions--tempValue--3a50n\" data-testid=\"TemperatureValue\">", "").replace("</span>]", "")

locationData = (str(location))
locationData = locationData.replace("[<h1 class=\"CurrentConditions--location--kyTeL\">", "").replace("</h1>]", "")

dayNightTemperature = (str(dayNightTemp))
dayNightTemperature = dayNightTemperature.replace("[<div class=\"CurrentConditions--tempHiLoValue--3SUHy\">", "").replace("<span data-testid=\"TemperatureValue\">", "").replace("</span> <!-- -->•<!-- --> <!-- -->Night<!-- -->", "").replace("</span></div>]", "").replace("Day<!-- -->", "")


finalTempRecord = "Current Temperature at " + locationData + " is " + currentTemperature + "\nDay: " + dayNightTemperature[1:4] + ", Night: " + dayNightTemperature[5:8]
print(finalTempRecord)